### PR TITLE
(Feature) Import contract

### PR DESCRIPTION
**Pull request by vbaranov**
Import a new type of account: smart-contract with the ability to execute transactions on it and call the data from it.

This type of account (address and ABI) is saved in the keyrings as a usual account.

*A life cycle of reading the data from the contract*:
 - choose saved "contract" account
 - click 'send' on the main screen
 - in the list of contract methods, choose the method to call
 - fill the appeared input fields and click 'Call data'
 - the result will be in 'Output' field

*A life cycle of executing the data from the contract*:
 - choose saved "contract" account
 - click 'send' on the main screen
 - in the list of contract methods, choose the method to execute
 - fill the appeared input fields and click 'Next'
 - in the appeared screen with the list of unlocked accounts choose the account to execute transaction on the contract and click 'Next'
 - confirm transaction (as usual) to contract. It will be executed under account selected in the list on the previous step.

Screenshots of the feature:

Import contract:

screen shot 2018-12-04 at 18 31 45

Execute transaction: 

screen shot 2018-12-04 at 18 33 13

image

Call contract's data:

screen shot 2018-12-04 at 18 39 42

Build on top of https://github.com/poanetwork/nifty-wallet/pull/209 (should merged after it)

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Error if transfered  value isn't integer
Tested with contract `0x06f0fE2C6be188b55049dA39C9D7CA6ee9b6Bf7c` , Ropsten
Owner's private key `ba98116a7d4b98f22f113c59448b9cc69f916d75f35d51f088b64b483fd0b8ca`

screen shot 2018-12-04 at 17 41 28

**Comment by dennis00010011b** [comment]
@vbaranov 
Custom token detection failed if token contract's account has been imported to NW
Steps:
 1. Import token contract account , ex `0x43916f2a13e73fb55f40BA6129FF6b7940D66408` , Ropsten
 2. Switch to any owned account and add token with address from step#1 `0x43916f2a13e73fb55f40BA6129FF6b7940D66408`

Expected:
 - token should be detected  since token exists

Actual:
 - token not found

screen shot 2018-12-04 at 18 08 48

**Comment by dennis00010011b** [comment]
@vbaranov 
Method execution: if method needs the  contract  executor (ex. `transfer`) then NW switches to this account after confirm transaction
Steps:
 1. Import contract `0x43916f2a13e73fb55f40BA6129FF6b7940D66408`, Ropsten
 2. Execute method transfer, use any account as an contract executor
 3. Confirm transaction

Expected result: current account should be imported contract account
Actual result: current account is contract executor

https://www.useloom.com/share/23bebcae4430430bbb1ff050bca6323d

**Comment by dennis00010011b** [comment]
@vbaranov 
enabled to  select many accounts as a contract executor

screen shot 2018-12-04 at 18 58 12

**Comment by dennis00010011b** [comment]
@vbaranov 
Titles should be align
screen shot 2018-12-04 at 19 09 22

**Comment by dennis00010011b** [comment]
@vbaranov 
Can import duplicate contract's  accounts, with the same addresses and ABI. Such accounts have the same name in NW
screen shot 2018-12-04 at 19 32 55

**Comment by dennis00010011b** [comment]
@vbaranov 
There is no checking that contract exist and verified in current network. Possible to add any non-existing contract account

**Comment by dennis00010011b** [comment]
@vbaranov 
FF: Choose contract executor - list of executors isn't scrollable to down end

screen shot 2018-12-04 at 20 07 59

**Comment by vbaranov** [comment]
@dennis00010011b 

>Needs to disable option export private key for contract's accounts (like for hw accounts)

>Account menu: green labels have different sizes for imported and contract values

>Custom token detection failed if token contract's account has been imported to NW

>Second call of the method balanceOf() leads to error message

>enabled to select many accounts as a contract executor

>Can import duplicate contract's accounts, with the same addresses and ABI. Such accounts have the same name in NW

>FF, Choose contract executor:

All should be fixed


>Error if transferred value isn't integer. Looks like value in wei goes to method's parameter

Yes, exactly. I think we don't need to change input interfaces, that contract has. Smart-contract expects an integer value. But agree, that validation should be improved. Let's make in a separate issue/PR.


>Method execution: if method needs the contract executor (ex. transfer) then NW switches to this account after confirm transaction

Yes, this is how it has been implemented now. Let's create a seprate issue for this enhancement.


>Titles should be align

It has been made such a way to fit the current design so far. But maybe, it is a good idea to change alignment, like you propose, in the future. I will think about it.


>There is no checking that contract exist and verified in current network. Possible to add any non-existing contract account

It shouldn't be verified to make calls to it. Though, address could be validated. Maybe, let's create a separate issue for that?

**Comment by dennis00010011b** [comment]
@vbaranov 
>Custom token detection failed if token contract's account has been imported to NW

Issue is still here, error message if attempt to add custom token but this token has been imported as contract account
FireFox, `0x43916f2a13e73fb55f40BA6129FF6b7940D66408`, Ropsten
screen shot 2018-12-05 at 10 28 20

**Comment by dennis00010011b** [comment]
>Can import duplicate contract's accounts, with the same addresses and ABI. Such accounts >have the same name in NW

Still here 
FireFox, 0x43916f2a13e73fb55f40BA6129FF6b7940D66408, Ropsten
screen shot 2018-12-05 at 10 41 07

**Comment by dennis00010011b** [comment]
@vbaranov 
One more thing. 
Since for importing the contract account an user should copy/paste two parameters (address and ABI)  it is impossible to use NW in popup mode. NW closes each time when user copy address or ABI  from source(ex. etherscan), but user can't paste two parameters in the same time. Possible solution could be memorize the address that has entered before (how address input works on 'Send Transaction' screen  )

https://www.useloom.com/share/98915c3e2bd049d59220e253ced42a6e

**Comment by vbaranov** [comment]
@dennis00010011b 

>Issue is still here, error message if attempt to add custom token but this token has been imported as contract account

Thanks, fixed https://github.com/poanetwork/nifty-wallet/pull/212/commits/842e6a39a41d4ea97c1f7d4a91e3f425a8074eb4

>Can import duplicate contract's accounts, with the same addresses and ABI. Such accounts >have the same name in NW
>Still here

Could you please check it once more on a clean install? I can not reproduce it anymore.

>One more thing.
Since for importing the contract account an user should copy/paste two parameters (address and ABI) it is impossible to use NW in popup mode. NW closes each time when user copy address or ABI from source(ex. etherscan), but user can't paste two parameters in the same time. Possible solution could be memorize the address that has entered before (how address input works on 'Send Transaction' screen )

Yes, very important thought! I will take care of this: we could mitigate it, at least, with ABI autodetection for verified contracts.

**Comment by dennis00010011b** [comment]
@vbaranov 
>Can import duplicate contract's accounts, with the same addresses and ABI. Such accounts >have the same name in NW

It fixed

**Comment by vbaranov** [comment]
https://github.com/poanetwork/nifty-wallet/pull/212/commits/a9d19b404441d0b454d27f6f589a92ef99158a72:
 - Nifty Wallet will be trying to get contract ABI by inserted address from BlockScout API at importing
 - And, also, validation at importing, that the address is contract, has been added

**Comment by dennis00010011b** [comment]
@vbaranov 
Button 'Import' could be disabled if contract doesn't exist or field ABI is empty
screen shot 2018-12-06 at 11 44 08

**Comment by dennis00010011b** [comment]
@vbaranov 
Should be ability to copy fetched ABI
screen shot 2018-12-06 at 12 34 50

**Comment by dennis00010011b** [comment]
@vbaranov 
ABI is fetched partly
Ex. POA, `0xb87b6077d59b01ab9fa8cd5a1a21d02a4d60d358`

Verified on BlockScout:
```
[{"type":"function","stateMutability":"view","payable":false,"outputs":[{"type":"address","name":""}],"name":"proxyOwner","inputs":[],"constant":true},{"type":"function","stateMutability":"nonpayable","payable":false,"outputs":[],"name":"upgradeTo","inputs":[{"type":"uint256","name":"version"},{"type":"address","name":"implementation"}],"constant":false},{"type":"function","stateMutability":"view","payable":false,"outputs":[{"type":"uint256","name":""}],"name":"version","inputs":[],"constant":true},{"type":"function","stateMutability":"view","payable":false,"outputs":[{"type":"address","name":""}],"name":"implementation","inputs":[],"constant":true},{"type":"function","stateMutability":"view","payable":false,"outputs":[{"type":"address","name":""}],"name":"upgradeabilityOwner","inputs":[],"constant":true},{"type":"function","stateMutability":"payable","payable":true,"outputs":[],"name":"upgradeToAndCall","inputs":[{"type":"uint256","name":"version"},{"type":"address","name":"implementation"},{"type":"bytes","name":"data"}],"constant":false},{"type":"function","stateMutability":"nonpayable","payable":false,"outputs":[],"name":"transferProxyOwnership","inputs":[{"type":"address","name":"newOwner"}],"constant":false},{"type":"fallback","stateMutability":"payable","payable":true},{"type":"event","name":"ProxyOwnershipTransferred","inputs":[{"type":"address","name":"previousOwner","indexed":false},{"type":"address","name":"newOwner","indexed":false}],"anonymous":false},{"type":"event","name":"Upgraded","inputs":[{"type":"uint256","name":"version","indexed":false},{"type":"address","name":"implementation","indexed":true}],"anonymous":false}]

```



Fetched by NW

```
[{"constant":true,"inputs":[],"name":"proxyOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"version","type":"uint256"},{"name":"implementation","type":"address"}],"name":"upgradeTo","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"version","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"implementation","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"upgradeabilityOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"version","type":"uint256"},{"name":"implementation","type":"address"},{"name":"data","type":"bytes"}],"name":"upgradeToAndCall","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferProxyOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":false,"name":"previousOwner","type":"address"},{"indexed":false,"name":"newOwner","type":"address"}],"name":"ProxyOwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"version","type":"uint256"},{"indexed":true,"name":"implementation","type":"address"}],"name":"Upgraded","type":"event"}]

```

**Comment by vbaranov** [comment]
@dennis00010011b 

>Button 'Import' could be disabled if contract doesn't exist or field ABI is empty

Disabling has been added https://github.com/poanetwork/nifty-wallet/pull/212/commits/848e4c81ee4bd13ba318032a13251eb316edb9d2

>Should be ability to copy fetched ABI

Copy button has been added https://github.com/poanetwork/nifty-wallet/pull/212/commits/aaf746862cad90a31e2da5022f60c6415be68cd0

>ABI is fetched partly

Actually, ABIs are the same, but the order of properties in JSON objects are reordered. I.e. an order of JSON properties in ABI from Blockscout API are ordered by the property name, but in the Blockscout contract page they are ordered by another way. I don't know, this is a feature or a bug @acravenho.

>weird error message if method required address but address field empty

Yes, the validation of inputs for contracts' methods is native. E.g. this is what returns when you are trying to ABI encode functions with input parameters.

**Comment by vbaranov** [comment]
The ability to copy ABI encoded function call has been added https://github.com/poanetwork/nifty-wallet/pull/212/commits/5ccda3c9a4b84c6a64f55f2c6e9d4dd87ed0eab5

screen shot 2018-12-07 at 20 05 17

**Comment by dennis00010011b** [comment]
@vbaranov 
Execute Method: there is no validation of parameter if click button 'Next' , but parameters still validated by clicking button 'Copy ABI encoded'

**Comment by fvictorio** [comment]
@vbaranov I deployed an ERC20 contract in sokol (address `0x3d71971291CeD21D88Cb1f6f121C915871B6CF5c`) but when I import it in Nifty Wallet it is added like a regular account.

I went to "Import account", changed the select box to "Contract", added that address and pasted the ERC20 ABI.

**Comment by vbaranov** [comment]
@fvictorio 
Repeated the same for the mentioned account - works for me.
screen shot 2018-12-11 at 22 51 28

Could you specify, does it have a `Contract` label? Does the screen with methods of contract open when you click to 'Send' button? What are the steps to reproduce this issue?

**Comment by vbaranov** [comment]
@dennis00010011b 
>Execute Method: there is no validation of parameter if click button 'Next' , but parameters still validated by clicking button 'Copy ABI encoded'

Thanks, actually, validation was ignored for 'Next' button. Now, I check the status of method ABI encoding. Fixed here https://github.com/poanetwork/nifty-wallet/pull/212/commits/715668a1b6a4c79d8160dc568c6d7c2e5227ee2f

**Comment by fvictorio** [comment]
> Does the screen with methods of contract open when you click to 'Send' button?

My bad, that was the step I was missing.

**Comment by vbaranov** [comment]
@fernandomg @patitonar thank you for the valuable suggestions. I keep them in mind for 4.10+ releases. All of them are conjugated with some sort of refactoring.

**Pull request merged**
