### PR TITLE
(Feature) Multiple outputs fields for contract calls

### PR DESCRIPTION
**Pull request by vbaranov**
Built from https://github.com/poanetwork/nifty-wallet/pull/212

Multiple outputs fields support for calling methods has been added for contract type account.

screen shot 2018-12-11 at 19 19 19

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Execute method:should be ability to copy output data (at least addresses), needs add copy icons

**Comment by dennis00010011b** [comment]
@vbaranov 
FireFox :  screen Execute Method isn't scrollable if multiply outputs present
screen shot 2018-12-11 at 14 50 32

**Comment by dennis00010011b** [comment]
@vbaranov 
NW isn't usable in popup mode if user want to call method with two and more input parameters. User needs fill out two fields but can't copy/paste two parameters in the same time. 
screen shot 2018-12-11 at 14 50 32

**Comment by vbaranov** [comment]
@dennis00010011b 
>Execute method:should be ability to copy output data (at least addresses), needs add copy icons

Good idea. Added here https://github.com/poanetwork/nifty-wallet/pull/219/commits/267807fede126d6b145b1152351daef3aa549fe4

**Comment by vbaranov** [comment]
@dennis00010011b 
>FireFox : screen Execute Method isn't scrollable if multiply outputs present

Fixed https://github.com/poanetwork/nifty-wallet/pull/219/commits/fed6cee26ec5b03805382de24965ac3d571b39ab

**Comment by vbaranov** [comment]
>NW isn't usable in popup mode if user want to call method with two and more input parameters. User needs fill out two fields but can't copy/paste two parameters because the input field's value is lost after each closing NW

Yeah, thinking about web page implementation. In a separate PR.

**Comment by dennis00010011b** [comment]
@vbaranov 
LGTM, except minor UI issue in FireFox
screen shot 2018-12-14 at 10 11 01

**Comment by dennis00010011b** [comment]
@vbaranov 
Execute method returns incorrect value for uint16 and more.  Value 'cutted'  to uint8
Contract `0x8ba3f8618a33cd3f155477e889295a4c5ab52ae4`, Sokol
Method `returnUint`, input data `11223344556677889911223344` , output `11223344556677888000000000`

screen shot 2018-12-17 at 23 48 48

**Comment by dennis00010011b** [comment]
@vbaranov 
Execute method always shows `true` for boolean return 
 Contract `0x8ba3f8618a33cd3f155477e889295a4c5ab52ae4`, Sokol
Method `returnBoolean`
screen shot 2018-12-17 at 23 55 30

**Comment by dennis00010011b** [comment]
@vbaranov 
Added types of returned values :bytes, int etc
`0xab6f1fad0fb4bf7efa253210698c02bfd29ab370`  Sokol

**Comment by vbaranov** [comment]
@dennis00010011b 
>Execute method always shows true for boolean return
Contract 0x8ba3f8618a33cd3f155477e889295a4c5ab52ae4, Sokol
Method returnBoolean

Fixed https://github.com/poanetwork/nifty-wallet/pull/219/commits/f5b565256927f96aa918f35fbe3619d4d87c3f6b

**Comment by vbaranov** [comment]
@dennis00010011b 
>Execute method returns incorrect value for uint32 and more. Value 'cutted' to uint16
Contract 0x8ba3f8618a33cd3f155477e889295a4c5ab52ae4, Sokol
Method returnUint which simple returns input, input data 11223344556677889911223344 , output 11223344556677888000000000

Fixed https://github.com/poanetwork/nifty-wallet/pull/219/commits/f46bb26b5db36bb1bb25de574562918c351a25f3

**Comment by dennis00010011b** [comment]
@vbaranov 
Tested it. No issues were found

**Pull request merged**
