### PR TITLE
E2e contract multiply outputs

### PR DESCRIPTION
**Pull request by dennis00010011b**
Fixed e2e tests due DOM  was changed  in PR https://github.com/poanetwork/nifty-wallet/pull/219

### CODE REVIEW

**Comment by vbaranov** [comment]
@dennis00010011b could you please get upstream to resolve merging conflicts?

**Comment by dennis00010011b** [comment]
@vbaranov 
Done

**Comment by vbaranov** [comment]
@dennis00010011b also, update of package-lock.json breaks `test-deps` scenario in CI. Could we remove update of it from this PR?

**Comment by dennis00010011b** [comment]
@vbaranov 
Done

**Pull request merged**
