### PR TITLE
(Feature) Multiple Ledger accounts for one session

### PR DESCRIPTION
**Pull request by vbaranov**
**Problem**: In the current version of NW on every unlock of HD account, the previous HD account is removed from the list of accounts.

**Solution**: This PR makes possible to add multiple HD accounts once from one Ledger in one device session* and work with them until next unlock. 
Related changes in Ledger related dependency https://github.com/vbaranov/eth-ledger-bridge-keyring/commit/949e3786ed9c41f47f5e1ee676eef427d58bb0fc and https://github.com/vbaranov/eth-ledger-bridge-keyring/commit/097807e7971ad0d2792be89ce93428f688d0a178

*if device was forgotten, connecting it again and unlocking still will replace previously unlocked HD accounts
**PR is only for Ledger. Nothing is changed for Trezor: 1 device = 1 account.

screen shot 2018-12-21 at 20 05 36

### CODE REVIEW

**Comment by vbaranov** [comment]
@dennis00010011b does it relate to the current PR only or to `develop` branch also?

**Comment by dennis00010011b** [comment]
@vbaranov 
YEs

> @dennis00010011b does it relate to the current PR only or to `develop` branch also?

Yes, this issue in `develop`, but not in `master`

**Comment by vbaranov** [comment]
@dennis00010011b I reproduced this issue.

Got minor updates regarding hd wallets from upstream

If the issue is still reproducible for you:
- check, that you are using the latest version of firmware
- login/logout from Nifty Wallet
- reconnect your HD device

Let me know, if the issue is still there

**Comment by dennis00010011b** [comment]
@vbaranov 
Issue still here. But at the same time both Ledger and Trezor  work perfect  from master branch build and with MM.
In current build:
 1. App don’t check if device is disconnected, there is no error about. 
2. No error if waiting for long time  and can’t connect to device
3. For Trezor connection a full page opens instead popup
Tested with Ledger Nano S (firmware 1.4.2-latest), Trezor One

**Comment by vbaranov** [comment]
@dennis00010011b I've made downgrade of dependencies related to HD wallets. Could you please test once more?

**Comment by dennis00010011b** [comment]
@vbaranov 
All added accounts have the same name, the digit in name equals the amount of added accounts
screen shot 2018-12-24 at 10 44 53

**Comment by vbaranov** [comment]
@dennis00010011b I've tried to repeat this, but have no success. Looks like 1 account imported 13 times. Could you provide the steps to repeat this issue?

**Comment by dennis00010011b** [comment]
@vbaranov 
I still can reproduce the issue

**Comment by vbaranov** [comment]
@dennis00010011b Ledger bridge link has been updated to our custom one, built with the latest versions of LedgerHQ deps. I can't reproduce this issue anymore.

**Comment by dennis00010011b** [comment]
@vbaranov 

>This PR makes possible to add multiple HD accounts once from one Ledger in **one device** >**session** and work with them until next unlock.

Possible to select several accounts  but only one account will be added per session. 
For add one more account user should open again Menu->Connect HD and reconnect with Ledger.
Expected: all selected HD accounts  should be imported OR disable multiply selection

**Comment by vbaranov** [comment]
@dennis00010011b I can't reproduce this issue with a clean install of NW and newly connected device with the latest firmware version. Could you please provide steps to reproduce?

**Comment by dennis00010011b** [comment]
@vbaranov 
Tested with Ledger Nano S, firmware 1.4.2, app Ethereum v. 1.1.7
MacOS 10.13.6, Chrome
Steps:
 1. Build NW: 
- clone repo and switch to branch multiple-hardware
 - npm i
 - npm run start
2. Open latest Chrome
3. Go to Settings->More tools->Extension
4. Turn on Developer mode
5.Select Load unpacked, load from ~/dist/chrome
6. Connect Ledger, enter PIN, enter to preinstalled Ethereum app
7. Open NW->ConnectHD-> Ledger, click Connect
8. Select five accounts, click Unlock
9. Observe added accounts
Expected: five accounts should be imported
Actual: one account imported

https://www.useloom.com/share/7e21a1fc5cb24d2fb13e5e94b6fdf97f

**Comment by dennis00010011b** [comment]
> @dennis00010011b does it work as expected with _Legacy (MEW / MyCrypto)_ option?
Yes, no issues with `Legacy (MEW / MyCrypto)` option

**Comment by dennis00010011b** [comment]
@vbaranov 
Unlock Ledger: button 'Unlock' enabled by default (no selected accounts) if any account already has been imported before.
Steps:
 1. Connect Ledger, select `Legacy (MEW / MyCrypto)` option
 2. Import any account
 3. Connect Ledger
 4. Observe button 'Unlock'
Expected result: 
 - button 'Unlock' should be disabled since no account selected

Actual result:
 -  button 'Unlock' enabled by default 

https://www.useloom.com/share/c3556f97b9d44cc9bfa03cff186ac164

**Comment by vbaranov** [comment]
Thank you @dennis00010011b for the report. The feature should work for accounts from *Ledger live* path also now https://github.com/poanetwork/nifty-wallet/pull/237/commits/4b0c8456d29acfc07f5d568d74c93265d478f169

**Comment by vbaranov** [comment]
Found an issue, that unlocked HD account is always the last chosen HD account. Changing to another HD account in the accounts dropdown doesn't unlock it actually (NW is still trying to send tx from the last from the selected account from the HD accounts screen). Working on it.

**Comment by vbaranov** [comment]
>Found an issue, that unlocked HD account is always the last chosen HD account. Changing to another HD account in the accounts dropdown doesn't unlock it actually (NW is still trying to send tx from the last from the selected account from the HD accounts screen). Working on it.

Issue has been fixed https://github.com/poanetwork/nifty-wallet/pull/237/commits/204865b80b5d70ed83b8decfab2f0d86edd29177: changing of account in the dropdown list should unlock Ledger account

Also, fixed the issue, when ledger account is in the list, but not chosen, and we are trying to unlock it from HD wallets screen, then account will be unlocked, but not selected in the dropdown.

Please, let me know, if any issues exist with this PR.

**Comment by dennis00010011b** [comment]
@vbaranov 
Unlock Ledger: account is selected and button 'Unlock' enabled if any account already has been imported before.
Steps:
1. Connect Ledger
2 .Import several  accounts
3. Connect Ledger
4. Observe list of accounts and button 'Unlock'

Expected result:
 - no accounts should be selected

Actual result:
 - one account is selected

https://www.useloom.com/share/c30774ebc6244bd2afa60ab58e0260de

**Comment by dennis00010011b** [comment]
@vbaranov 
Number in name of  new imported/created accounts is not  in order if Ledger/Trezor accounts have been added. 
Example, if six Ledger accounts have been  added then new created/imported account/contract has name `Account 8` , not `Account 2`
screen shot 2018-12-27 at 13 06 45

**Comment by vbaranov** [comment]
@dennis00010011b 
>Unlock Ledger: account is selected by default if any account already has been imported before.

Yes, currently selected HD account is selected in the HD accounts screen. It makes sense in the case of radio buttons when selecting another address will automatically deselect the current one, but in the case of checkboxes, it doesn' make sense. Ok, will remove this behaviour.

>Number in name of new imported/created accounts is not in order if Ledger/Trezor accounts have been added.

Yes, this is intentional. The numeration is pass-through all types of accounts. I am not sure we could fix it without massive reorganization. I will keep it in mind in the future refactoring.

>If Ledger device was disconnected then imported accounts are unavailable.
Expected that Ledger's accounts should be observable (like it works for Trezor)

Due to a long connection timeout, connection to HD device/unlocking, it makes sense to move the connection to HD device right before sending tx. Will do. Thanks.

**Comment by dennis00010011b** [comment]
@vbaranov 
> Found an issue, that unlocked HD account is always the last chosen HD account. Changing >to another HD account in the accounts dropdown doesn't unlock it actually (NW is still trying >to send tx from the last from the selected account from the HD accounts screen). Working >on it.

This issue reproducible again.  There is no confirmation request on device's screen when try to send ether from account different that Ledge1 (see video)

https://www.useloom.com/share/5fed9bc8b9f44b7a8f44a41207c9d17d

**Comment by vbaranov** [comment]
@dennis00010011b 
>Yes, currently selected HD account is selected in the HD accounts screen. It makes sense in the case of radio buttons when selecting another address will automatically deselect the current one, but in the case of checkboxes, it doesn' make sense. Ok, will remove this behaviour.

Fixed https://github.com/poanetwork/nifty-wallet/pull/237/commits/83b90b775dfbcff84c290bc69814188d202d71dc

>Due to a long connection timeout, connection to HD device/unlocking, it makes sense to move the connection to HD device right before sending tx. Will do. Thanks.

Decided not to move this logic to pending tx page to not make it heavier. I left logic on account change in dropdown but in the background. https://github.com/poanetwork/nifty-wallet/pull/237/commits/56759f28e8123f62619604cc3f66e8fd4a9238f3 and https://github.com/poanetwork/nifty-wallet/pull/237/commits/5b7010f790a9ea1991b7f95a2eabd96c33c0e08d

screen shot 2018-12-28 at 17 12 11

**Comment by vbaranov** [comment]
@dennis00010011b 
>This issue reproducible again. There is no confirmation request on device's screen when try to send ether from account different that Ledge1 (see video)

I cannot reproduce it. Does it still exist for you?

**Comment by dennis00010011b** [comment]
@vbaranov 
> > This issue reproducible again. There is no confirmation request on device's screen when try to send ether from account different that Ledge1 (see video)
> 
> I cannot reproduce it. Does it still exist for you?

I cannot reproduce it anymore. 
Tested it , no issues were found

**Pull request merged**
